#ifndef QUERYTYPE_H
#define QUERYTYPE_H

enum class QueryType
{
    LOGIN,
    ADD_EMPLOYEE,
    ADD_ROLE_TO_EMPLOYEE,
    GET_ROLES,
    REMOVE_ROLE_FROM_EMPLOYEE,
    UPDATE_USER,
    UPDATE_PASSWORD,
    ADD_PRODUCT,
    GET_PRODUCT_CATEGORIES,
    ADD_PRODUCT_ORDER,
    ADD_PRODUCT_ORDER_DETAIL
};

#endif // QUERYTYPE_H
