#ifndef QUERYTYPE_H
#define QUERYTYPE_H

enum class QueryType
{
    LOGIN,
    ADD_EMPLOYEE,
    ADD_ROLE_TO_EMPLOYEE,
    GET_ROLES,
    REMOVE_ROLE_FROM_EMPLOYEE,
    UPDATE_USER,
    UPDATE_PASSWORD,
    ADD_PRODUCT,
    GET_PRODUCT_CATEGORIES,
    ADD_PRODUCT_ORDER,
    ADD_PRODUCT_ORDER_DETAIL,
    GET_PRODUCT,
    GET_PRODUCT_ORDER,
    GET_PRODUCT_BY_ORDER_ID,
    GET_CUSTOMER,
    ADD_CUSTOMER,
    GET_SERVICE_CATEGORIES,
    GET_CUSTOMER_BY_PHONE,
    ADD_SERVICE,
    ADD_SERVICE_ORDER_DETAIL,
    ADD_SERVICE_ORDER,
    GET_SERVICE_ORDER,
    GET_SERVICE_BY_ORDER_ID_FOR_CHECK,
    UPDATE_CUSTOMER,
    GET_MESSAGE,
    ADD_MESSAGE,
    UPDATE_MESSAGE_STATUS,
    GET_SERVICE,
    GET_SERVICE_BY_ORDER_ID,
    GET_SOLD_PRODUCT,
    GET_PRODUCT_ORDER_BY_ID,
    GET_PRODUCT_ORDER_BY_SELLER,
    GET_PRODUCT_ORDER_BY_DATE,
    GET_SOLD_PRODUCT_BY_CATEGORY,
    GET_SOLD_PRODUCT_BY_COST,
    GET_SOLD_PRODUCT_BY_CATEGORY_AND_COST,
    GET_UNSOLD_PRODUCT,
    GET_UNSOLD_PRODUCT_BY_BARCODE
};

#endif // QUERYTYPE_H
